import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const clashFont = localFont({
  src: [
    { path: "../public/fonts/clash-grotesk/ClashGrotesk-Medium.woff2", weight: "400" },
    { path: "../public/fonts/clash-grotesk/ClashGrotesk-Medium.woff2", weight: "700" },
  ],
  variable: "--font-clash",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashFont.className}`}>{children}</body>
    </html>
  );
}
